name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build
      run: ./gradlew --warning-mode all build
    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-failure-logs
        path: |
          missingdot/build/reports/
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: missing-dot-artifacts
        path: |
          missingdot/build/libs/*.jar
          missingdot/build/outputs/aar/*.aar

